default: &default
  adapter: postgresql
  encoding: unicode
  database: embarca
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
